### ISSUE TITLE
ORE error

### ISSUE THREAD

**Issue by JaghanKS** [jonclayden/ore#3] opened 2015-05-13 06:21 UTC
Greetings..!!!

I am working on oracle R 3.0.1 with the sentiment scoring program working fine in Development and UAT environment. Whereas in production environment the Oracle R 3.1.1 version is installed and the same program is not working fine and it throws the error as shown below:

I'm using ore.push command where i'm getting this issue. If I use ORE.PULL it is coming fine but if I run the rest of the code then following errors comes.

Error in get("r.dbObjs", envir = .ore.GlobalEnv) :
  object 'r.dbObjs' not found

Also attaching the screenshot for reference:

![image](https://cloud.githubusercontent.com/assets/12423836/7604830/9ed8438e-f972-11e4-8072-1c5366b18faf.png)

Please help to fix this issue asap as we are in near production migration.

**Comment by jonclayden** [comment] 2015-05-13 09:55
I'm afraid I have no idea what is going on here. There is no `ore.push` or `ore.pull` function, for a start, nor does any of the package's code reference an object called `r.dbObjs`. If you're sure that the issue is not with your code, then I would be much more able to help if you could provide a simple, self-contained, reproducible example demonstrating the problem.

**Comment by JaghanKS** [comment] 2015-05-13 10:06
Hi Clayden,

Please find below the code which we are using..

library(ORE)
ore.connect(user="dmuser", sid="orcl", password="dmuser", host="10.10.25.8", port=1521, all=TRUE)
ore.attach()
ore.sync()
df <- ore.pull(SENTIMENT_INFO)
ores <- data.frame(TOPIC_POSTED_DATE=df$TOPIC_POSTED_DATE,AUTHOR_NAME=df$AUTHOR_NAME,TELKOM_ID=df$TELKOM_ID,X_CUST_ID=df$X_CUST_ID,SCORING=df$SCORING,CONVERSATION=df$CONVERSATION,PRODUCT_INTEREST=df$PRODUCT_INTEREST,SRM_ID=df$SRM_ID)
ores$NEWSCORE <- 0
res <- ore.pull(ores)
pos = scan('/home/oracle/query/positive-words.txt', what='character', comment.char=';')
neg =scan('/home/oracle/query/negative-words.txt', what='character', comment.char=';')
library(plyr)
library(stringr)
score <- ore.rowApply(SENTIMENT_INFO, function(df) {
score.sentiment =function(sentences,pos.words,neg.words)
{
require(plyr)
require(stringr)
initial_sentence=sentences
sentence=sentences
        sentence = gsub('[[:punct:]]', '', sentence)
        sentence = gsub('[[:cntrl:]]', '', sentence)
        sentence = gsub('\\d+', '', sentence)
            sentence = tolower(sentence)
        word.list = strsplit(sentence, '\\s+')
        words = unlist(word.list)
        pos.matches = match(words, pos.words)
        neg.matches = match(words, neg.words)
        pos.matches = !is.na(pos.matches)
        neg.matches = !is.na(neg.matches)
        score = sum(pos.matches) - sum(neg.matches)
        return(score)
   }
##########################

pos = scan('/home/oracle/query/positive-words.txt', what='character', comment.char=';')
neg =scan('/home/oracle/query/negative-words.txt', what='character', comment.char=';')
        pos.words = c(pos, 'upgrade')
        neg.words = c(neg, 'wtf', 'wait','waiting', 'epicfail', 'mechanical')
       newscores = score.sentiment(df$MESSAGE_BODY,pos.words, neg.words)
        res= data.frame(TOPIC_POSTED_DATE=df$TOPIC_POSTED_DATE,AUTHOR_NAME=df$AUTHOR_NAME,TELKOM_ID=df$TELKOM_ID,X_CUST_ID=df$X_CUST_ID,SCORING=df$SCORING,CONVERSATION=df$CONVERSATION,PRODUCT_INTEREST=df$PRODUCT_INTEREST,SRM_ID=df$SRM_ID,NEWSCORE=newscores)
        res
    },
FUN.VALUE=ores
)
score1 <- ore.pull(score)
ore.create(score1, table="SCORING")

When running the above code in (Oracle Distribution of R version 3.0.1  (--) -- "Good Sport"
) it is running perfectly. Whereas in version (Oracle Distribution of R version 3.1.1  (--) -- "Sock it to Me") I'm getting the following error (Error in get("r.dbObjs", envir = .ore.GlobalEnv) :
  object 'r.dbObjs' not found)

Please help to fix this issue asap.

Thanks,

**Comment by jonclayden** [comment] 2015-05-13 10:11
This code does not use my package, but apparently something (Oracle-specific?) called `ORE` (note case). Please check the maintainer information for that package. `ore` is a regular expression library, not a database package.

**Comment by jonclayden** [comment] 2015-05-13 11:09
Closing as not relevant. I've added a comment to the `README` to deal with the possible confusion with Oracle R Enterprise.

**Closed by jonclayden** 2015-05-13 11:09 UTC
